### ISSUE TITLE
Add a link the readthedocs

### ISSUE THREAD

**Issue by tailaiw** [faustomorales/python-boilerplate#1]
I think it would be great to add the [link](https://faustomorales-python-boilerplate.readthedocs.io/en/latest/) to the readthedocs documentation in readme, so anyone who wanna try this template have an idea how the doc would look like.

**Comment by faustomorales** [comment]
Great idea! Implemented this in c2f1a63e2ec3bda393ba9d96b592c5862c64d44f. Thanks!
